COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:TEST',
    '//lib:org.apache.karaf.shell.console',
    '//incubator/api:onos-incubator-api',
    '//cli:onos-cli',
    '//utils/osgi:onlab-osgi',
    '//core/common:onos-core-common',
    '//apps/millimeterwave/psuccess:onos-apps-millimeterwave-psuccess',

]


osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
