COMPILE_DEPS = [
    '//lib:CORE_DEPS',
    '//lib:TEST',
    '//lib:org.apache.karaf.shell.console',
    '//lib:commons-math3',
    '//incubator/api:onos-incubator-api',
    '//cli:onos-cli',
    '//utils/osgi:onlab-osgi',
]


osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)
